addresses = ["Corso Bramante 39",
             "Corso Sebastopoli 308",
             "Via Monte Novegno 31",
             "Via Riccaldone 11",
             "Via Filadelfia 130",
             "Corso Maroncelli 35",
             "Via Bonfante 11",
             "Via San Pio V 34",
             "Via Dandolo 21",
             "Largo Saluzzo 36",
             "Via Abegg 4",
             "Via Ventimiglia 18",
             "Piazza Bengasi 26",
             "Via Guala 139",
             "Corso Orbassano 191",
             "Via Buenos Aires 4",
             "Corso Unione Sovietica 256",
             "Via Vigliani 89",
             "Via Pellico 24",
             "Via Garessio 24",
             "Via Cellini 21",
             "Via Martiri della Libertà 10",
             "Via Mazzini 36",
             "Via della Rocca 10",
             "Strada dei Tadini 5",
             "Strada degli Alberoni 12",
             "Via Artom 42",
             "Via Quarello 12",
             "Strada del Drosso 48",
             "Via Plava 99",
             "Via Fratelli Garrone 37",
             "Corso Agnelli 102",
             "Corso Galileo Ferraris 99",
             "Via San Secondo 53",
             "Corso Trento 8",
             "Corso Rosselli 110",
             "Corso Traiano 73",
             "Via Madama Cristina 88",
             "Via Rubino 18",
             "Corso Salvemini 3",
             "Via Taggia 6",
             "Via Pio VII 58",
             "Corso Corsica 56",
             "Corso Moncalieri 271",
             "Corso Giovanni Lanza 32",
             "Via Tetti Valfrè 2",
             "Strada consortile del Salino 20",
             "Via Braccini 1",
             ]

procedure_time_mapping = {"VISITASTRUTTURATO": 20,
                          "VISITAMEDICO": 20,
                          "VISITAINFERMIERE": 10,
                          "MIDLINE": 40,
                          "ECOGRAFIA": 15,
                          "ECG": 5,
                          "PRELIEVO": 5,
                          "INFUSIONESINGOLA": 5,
                          "INFUSIONEMULTIPLA": 15,
                          "TRASF-1": 15,
                          "TRASF-2": 45,
                          "MEDICAZIONEMIDLINE": 10,
                          "MEDICAZIONEDECUBITI": 40,  # may actually vary in 15-40
                          "CLISTERE": 10,
                          "TRAININGCAREGIVER": 15,
                          "SUPPORTOPSICOLOGICO": 20,
                          "PRESAINCARICO": 90,
                          "DIMISSIONE": 35
                          }

# average explicit occurrences per day
procedure_avg_occurrences_mapping = {"MIDLINE": 3,
                                     "ECOGRAFIA": 1,
                                     "ECG": 2,
                                     "PRELIEVO": 6,
                                     "TRASF-1": 1,
                                     "TRASF-2": 1,
                                     "MEDICAZIONEDECUBITI": 3,
                                     "CLISTERE": 2, # invented, since no explicit info was available
                                     "TRAININGCAREGIVER": 3,
                                     "SUPPORTOPSICOLOGICO": 2,
                                     # "PRESAINCARICO": 1,
                                     # "DIMISSIONE": 2,
                                     }
